import { useState } from "react"
import "./ProductDetail.css"
import { FAQ } from "./FAQ";

export function ProductDetails() {

    const [faq,setFaq] = useState([{
        ques: "Can I test Brizy AI for free before buying a plan?",
        answer: "Yes! You get 5 free website generations with Brizy AI (start on www.ai.brizy.io), plus a 14-day free trial in Brizy Cloud, where you can generate unlimited websites and explore all the features, including the drag-and-drop editor."
    },{
        ques: "How can I customize my website built with Brizy AI?",
        answer: "You can easily customize your AI-generated website using Brizy Cloud’s drag-and-drop editor—it's included in all AI builder plans, and there’s no need for coding!"
    },{
         ques: "What if I don’t like the website AI creates?",
        answer: "You can fully customize it—or get a refund within 30 days!"
    },{
        ques: "Will my website be mobile-friendly?",
       answer: "Yes! Brizy AI builds mobile-optimized websites by default. Whether your visitors are on desktops, tablets, or smartphones, your site will look flawless on any device."
   },{
        ques: "Do I need coding skills to use Brizy AI?",
        answer: "Nope! Brizy AI does all the heavy lifting. Once your site is generated, you can easily tweak it using our drag-and-drop editor—no coding required."
    }]);

   return (
    <section className="product-detail-sec">
        <div className="product-head-div">
            <h1>Brizy AI Product Information</h1>
        </div>
        <main className="product-details-main">
            <div className="what-detail-box">
                <div className="question-box">
                    <h1>What Is Brizy AI</h1>
                </div>
                <div className="answer-box">
                  <p>Ready to build websites in seconds, not weeks? Brizy AI is a robust website builder that’s made a major impact, with over 5 million websites generated by users worldwide. Designed for speed and simplicity, it empowers users to create beautiful, fully-structured sites in minutes. Just connect your Google My Business profile or give a brief description of your business, and Brizy’s AI takes care of the rest—handling the structure, text, images, and basic design. Once generated, the Brizy Cloud editor lets users personalize every detail for a unique, polished look. The platform’s no-code approach is perfect for anyone, from freelancers to B2B services like agencies and SaaS providers. Brizy AI even comes in a white-label version, enabling agencies and hosting companies to embed this efficient tool within their own platforms, creating a seamless user experience for their clients. With built-in SEO optimization and mobile responsiveness, Brizy AI ensures sites look great and perform well on any device. Its quick setup, intuitive editing, and scalable white-label solution make it a go-to for businesses and agencies aiming to automate initial site-building tasks and focus on growth.</p>
                </div>
            </div>
            <div className="what-detail-box ">
                <div className="question-box ">
                    <h1>How To Use Brizy AI?</h1>
                </div>
                <div className="answer-box ">
                  <p>No learning curves. No wasted time. Just answer a few quick questions, or let Brizy AI pull in details from your Google Business Profile, and watch the magic happen. Launch Your Website in 3 Simple Steps: 1. Describe or connect your business with Google Business Profile 2. AI generates your website 3. Customize as much as you like in Brizy editor and hit publish. You're live!</p>
                </div>
            </div>
            <div className="what-detail-box ">
                <div className="question-box ">
                    <h1>Brizy AI Core Features</h1>
                </div>
                <div className="answer-box ">
                 <ul>
                    <li>Google Business Profile integration</li>
                    <li>Full website customization options</li>
                    <li>Unlimited AI generations (whole page, elements, copy, image)</li>
                    <li>SEO & responsive ready</li>
                    <li>Multi-page or landing page</li>
                    <li>Multi-language</li>
                 </ul>
                </div>
            </div>
            <div className="what-detail-box ">
                <div className="question-box ">
                    <h1>Brizy AI Use Cases</h1>
                </div>
                <div className="answer-box ">
                 <ul>
                    <li>#1 Instant Website Generation - AI creates fully designed, industry-specific websites</li>
                    <li>#2 Customizable Prototypes - Quickly refine and tailor sites to client needs</li>
                    <li>#3 Scalable & Efficient - Handle more projects with less manual effort</li>
                    <li>#4 New Revenue Stream - Offer a branded website builder as an add-on service</li>
                 </ul>
                </div>
            </div>
            <div className="what-detail-box ">
                <div className="question-box ">
                    <h1>FAQ From Brizy AI</h1>
                </div>
                <div className="answer-box ">
                 {faq.map((q,i) => {
                    return <FAQ question={q.ques} answer={q.answer}/>
                 })}
                </div>
            </div>
            <div className="what-detail-box ">
                <div className="question-box ">
                    <h1>Brizy AI Support Email & Customer service contact & Refund contact etc.</h1>
                </div>
                <div className="answer-box ">
                  <p>More Contact, visit the contact us page()</p>
                </div>
            </div>
            <div className="what-detail-box ">
                <div className="question-box ">
                    <h1>Brizy AI Login</h1>
                </div>
                <div className="answer-box ">
                <ul>
                    <li>Brizy AI Company name: .</li>
                    <li>Brizy AI Company address: .</li>
                    <li>More about Brizy AI, Please visit the about us page().</li>
                 </ul>
                </div>
            </div>
            <div className="what-detail-box ">
                <div className="question-box ">
                    <h1>Brizy AI Sign Up</h1>
                </div>
                <div className="answer-box ">
                  <p>Brizy AI Login Link:</p>
                </div>
            </div>
        </main>
    </section>
   )
}