import "./ProductDetail.css"

export function ProductDetails() {
   return (
    <section className="product-detail-sec">
        <div className="product-head-div">
            <h1>Brizy AI Product Information</h1>
        </div>
        <main className="product-details-main">
            <div className="what-detail-box">
                <div className="question-box">
                    <h1>What Is Brizy AI</h1>
                </div>
                <div className="answer-box">
                  <p>Ready to build websites in seconds, not weeks? Brizy AI is a robust website builder that’s made a major impact, with over 5 million websites generated by users worldwide. Designed for speed and simplicity, it empowers users to create beautiful, fully-structured sites in minutes. Just connect your Google My Business profile or give a brief description of your business, and Brizy’s AI takes care of the rest—handling the structure, text, images, and basic design. Once generated, the Brizy Cloud editor lets users personalize every detail for a unique, polished look. The platform’s no-code approach is perfect for anyone, from freelancers to B2B services like agencies and SaaS providers. Brizy AI even comes in a white-label version, enabling agencies and hosting companies to embed this efficient tool within their own platforms, creating a seamless user experience for their clients. With built-in SEO optimization and mobile responsiveness, Brizy AI ensures sites look great and perform well on any device. Its quick setup, intuitive editing, and scalable white-label solution make it a go-to for businesses and agencies aiming to automate initial site-building tasks and focus on growth.</p>
                </div>
            </div>
            <div className="what-detail-box ">
                <div className="question-box ">
                    <h1>How To Use Brizy AI?</h1>
                </div>
                <div className="answer-box ">
                  <p>No learning curves. No wasted time. Just answer a few quick questions, or let Brizy AI pull in details from your Google Business Profile, and watch the magic happen. Launch Your Website in 3 Simple Steps: 1. Describe or connect your business with Google Business Profile 2. AI generates your website 3. Customize as much as you like in Brizy editor and hit publish. You're live!</p>
                </div>
            </div>
            <div className="what-detail-box ">
                <div className="question-box ">
                    <h1>Brizy AI Core Features</h1>
                </div>
                <div className="answer-box ">
                 <ul>
                    <li>Google Business Profile integration</li>
                    <li>Full website customization options</li>
                    <li>Unlimited AI generations (whole page, elements, copy, image)</li>
                    <li>SEO & responsive ready</li>
                    <li>Multi-page or landing page</li>
                    <li>Multi-language</li>
                 </ul>
                </div>
            </div>
            <div className="what-detail-box ">
                <div className="question-box ">
                    <h1>Brizy AI Use Cases</h1>
                </div>
                <div className="answer-box ">
                 <ul>
                    <li>#1 Instant Website Generation - AI creates fully designed, industry-specific websites</li>
                    <li>#2 Customizable Prototypes - Quickly refine and tailor sites to client needs</li>
                    <li>#3 Scalable & Efficient - Handle more projects with less manual effort</li>
                    <li>#4 New Revenue Stream - Offer a branded website builder as an add-on service</li>
                 </ul>
                </div>
            </div>
        </main>
    </section>
   )
}